# Wine Demo
# An example of Service, Agent, Function, and View definitions in YAML
# For simplicity, all definitions are in this single YML file.
# For production apps, we recommend splitting out into separate files.

service:
  name: wines_demo
  display_name: Wine Demo
  description: Helping you select the best wines
  logo_url: /assets/logo.jpg
  hero_image_url: /assets/hero.jpg
  state: hidden

  text_number: +14151118888

  starter_agent_name: wine_selector

  # Make the background color of messages from the AI red in the web UX
  custom_css: |
    .chat-other-message {
        background-color: red;
        color: black;
    }

agent:
  name: wine_selector
  display_name: Tarquin
  default_service: wines_demo
  avatar_url: /assets/logo.jpg
  description: Helps you find great wines that will match your taste
  objective: |
    You are an expert sommelier with a broad and deep knowledge of wines from around the world.
    Your job is to make recommendations to the user of varietals, regions, vintages, and specific wines they might like.
    You should first ask for their name. When you have their name, record it by calling the wines__functions__set_name function.
    Your ultimate job is to create a personal tasting list for the user - a list of 10 wines you think they MUST try.
    Ask whatever questions you deem appropriate to build that list for the user.
    A good place to start is to ask them about the wines they already like and why they like them.
    When you have built the users personal tasting list, record it by calling the wines__functions__create_tasting_list function, passing in
    the tasting list in JSON in the following format:
    {"tasting_list": [
      {
        "name": "Château Margaux 2015",
        "producer": "Château Margaux",
        "region": "Bordeaux",
        "subregion": "Margaux",
        "country": "France",
        "appellation": "AOC Margaux",
        "vintage": 2015
      },
      {...}
    ]}

  initial_message: |
    Hi, I'm Tarquin.
    I love to recommend wines.
    Is there a particular kind of wine that you already know you love?

  default_suggestions: Recommend White Wines,Recommend Red Wines

  # Declare Functions that the LLM has access to, and pass any needed config to them
  functions:
    - name: wines.functions.set_name
    - name: wines.functions.create_tasting_list
      config:
        sommelier: Tarquin

  # Setup custom Tunings
  tunings:
    - prompt: What's your favorite wine?
      response: Champagne is my favorite!
    - prompt: What is better - red wine or white wine?
      response: I can't possibly decide. There are great red and white wines!

  ### How to tell the agent about MCP servers it can call
  #  mcp_servers: |
  #    {
  #      "mcpServers": {
  #          "helloworld": {
  #              "command": "foo",
  #              "args": [
  #                  "bar",
  #              ]
  #          }
  #      }
  #    }

  ### How to define the specific vendor, model, etc to use (defaults to OpenAI gpt-4o-mini)
  #    preferred_vendor: Anthropic
  #    preferred_model: claude-3-sonnet-20240229
  #    temperature: 0.5

# Implement functions
functions:
  - function:
    name: wines.functions.set_name
    description: Record the user's name
    parameters:
      type: object
      properties:
        user_name:
          type: string
          description: the user's name
      required:
        - user_name
    implementation_type: js
    # language=javascript
    implementation: |
      const store = chat.getStore();
      store.scopeTo({chat: chat});
      store.set("user_name", params["user_name"]);
      ({success: true, message: "The user's name has been stored"});

  - function:
    name: wines.functions.create_tasting_list
    description: Store a wine tasting list for the user
    parameters:
      type: object
      properties:
        tasting_list:
          type: string
          description: the user's recommended tasting list in JSON format
      required:
        - tasting_list
    implementation_type: js
    # language=javascript
    implementation: |
      const store = chat.getStore();
      store.scopeTo({chat: chat});
      store.set("tasting_list", params["tasting_list"]);
      chat.setView("wines.views.tasting_list");
      ({success: true, message: "The user's tasting has been stored"});

# Implement Views
views:
  - view:
    name: wines.views.tasting_list
    description: Show the user their recommended tasting list
    # language=css
    custom_css: |
      #tasting-list {
          padding: 20px;
      }
    # language=html
    implementation: |
      <div id="tasting-list">
          <h1 class="chat-primary-text">Your Tasting Menu:</h1>
          <ol>
            <% store.get("tasting_list").each do |wine| %>
              <li class="chat-primary-text">
                  <%= wine["vintage"] %> <%= wine["name"] %>
              </li>
            <% end %>
          </ol>
      </div>